<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\Product;
use App\Models\PurchaseOrder;
use App\Models\PurchaseOrderItem;
use App\Models\PurchaseRequest;
use App\Models\PurchaseRequestItem;
use App\Models\Supplier;
use App\Models\User;
use App\Models\Warehouse;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class PurchasingSeeder extends Seeder
{
    public function run(): void
    {
        $company = Company::first();
        if (!$company) {
            $this->command->error('No company found. Please run DemoDataSeeder first.');
            return;
        }

        $user = User::first();
        $warehouse = Warehouse::where('is_default', true)->first() ?? Warehouse::first();
        $products = Product::where('is_purchased', true)->get();

        if ($products->isEmpty()) {
            $this->command->error('No purchasable products found. Please run DemoDataSeeder first.');
            return;
        }

        // Cleanup existing data to avoid duplicates
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        PurchaseOrderItem::truncate();
        PurchaseOrder::truncate();
        PurchaseRequestItem::truncate();
        PurchaseRequest::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // 1. Create Suppliers
        $suppliers = [
            ['name' => 'PT Mitra Baja Utama', 'code' => 'SUP-001'],
            ['name' => 'Global Steel Corp', 'code' => 'SUP-002'],
            ['name' => 'CV Supplier Besi', 'code' => 'SUP-003'],
            ['name' => 'Inti Material Teknik', 'code' => 'SUP-004'],
            ['name' => 'Adi Mandiri Perkasa', 'code' => 'SUP-005'],
            ['name' => 'Mega Industrial Supply', 'code' => 'SUP-006'],
        ];

        foreach ($suppliers as $sup) {
            Supplier::firstOrCreate(
                ['code' => $sup['code']],
                [
                    'company_id' => $company->id,
                    'name' => $sup['name'],
                    'email' => strtolower(str_replace(' ', '', $sup['name'])) . '@example.com',
                    'phone' => '021-' . rand(1000000, 9999999),
                    'address' => 'Jl. Ray Industrial Estate No. ' . rand(1, 100),
                    'city' => 'Jakarta',
                    'is_active' => true,
                ]
            );
        }

        $supplierModels = Supplier::all();

        // 2. Create Purchase Orders (Last 6 Months)
        $statuses = ['ordered', 'received', 'completed', 'approved', 'draft', 'cancelled'];
        
        // Generate ~150 POs for higher density
        for ($i = 0; $i < 150; $i++) {
            $date = Carbon::now()->subDays(rand(1, 180));
            $supplier = $supplierModels->random();
            $status = $statuses[array_rand($statuses)];

            // Favor "completed" and "ordered" for older dates to make charts look good
            if ($date->lt(Carbon::now()->subMonths(2))) {
                $status = rand(0, 10) > 2 ? 'completed' : 'cancelled';
            }

            $po = PurchaseOrder::create([
                'company_id' => $company->id,
                'po_number' => 'PO-' . $date->format('ym') . '-' . str_pad($i + 1, 4, '0', STR_PAD_LEFT),
                'supplier_id' => $supplier->id,
                'warehouse_id' => $warehouse->id,
                'order_date' => $date,
                'expected_date' => $date->copy()->addDays(7),
                'status' => $status,
                'currency' => 'IDR',
                'exchange_rate' => 1,
                'subtotal' => 0, // Calculated below
                'tax_percent' => 11,
                'tax_amount' => 0, // Calculated below
                'total' => 0, // Calculated below
                'created_by' => $user->id,
                'notes' => 'Generated by PurchasingSeeder',
                'created_at' => $date,
                'updated_at' => $date,
            ]);

            // Add Items
            $itemCount = rand(1, 5);
            $subtotal = 0;

            for ($j = 0; $j < $itemCount; $j++) {
                $product = $products->random();
                $qty = rand(10, 100);
                $price = $product->cost_price > 0 ? $product->cost_price : rand(10000, 500000);
                $rowTotal = $qty * $price;

                PurchaseOrderItem::create([
                    'purchase_order_id' => $po->id,
                    'product_id' => $product->id,
                    'description' => $product->name,
                    'qty' => $qty,
                    'unit_price' => $price,
                    'subtotal' => $rowTotal,
                    'qty_received' => ($status === 'received' || $status === 'completed') ? $qty : 0,
                ]);

                $subtotal += $rowTotal;
            }

            // Update PO Totals
            $tax = $subtotal * 0.11;
            $po->update([
                'subtotal' => $subtotal,
                'tax_amount' => $tax,
                'total' => $subtotal + $tax,
            ]);
        }

        // 3. Create Purchase Requests (Recent)
        // Ensure some are 'draft' for the Pending Approvals KPI
        for ($i = 0; $i < 15; $i++) {
            $isDraft = $i < 5; // 5 drafts
            $date = Carbon::now()->subDays($isDraft ? rand(0, 5) : rand(5, 30));
            $status = $isDraft ? 'draft' : (rand(0, 1) ? 'approved' : 'rejected');

            $pr = PurchaseRequest::create([
                'company_id' => $company->id,
                'pr_number' => 'PR-' . $date->format('ym') . '-' . str_pad($i + 1, 4, '0', STR_PAD_LEFT),
                'department' => ['Production', 'Maintenance', 'IT', 'General'][rand(0, 3)],
                'requester' => $user->name,
                'request_date' => $date,
                'status' => $status,
                'notes' => $isDraft ? 'Urgent request regarding machine breakdown' : 'Routine replenishment',
                'created_by' => $user->id,
                'created_at' => $date,
                'updated_at' => $date,
            ]);

            $pr->items()->create([
                'product_id' => $products->random()->id,
                'qty' => rand(5, 50),
                'description' => 'Urgent replacement',
            ]);
        }
        
        $this->command->info('Purchasing data seeded successfully.');
    }
}
