<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;
use App\Models\Product;
use App\Models\SalesForecast;
use App\Models\DeliverySchedule;
use App\Models\SalesOrder;
use App\Models\SalesOrderItem;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class SalesPlanningSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get some existing customers and products
        // If not enough, create some
        if (Customer::count() < 3) {
            Customer::factory()->count(5)->create();
        }
        if (Product::count() < 5) {
            Product::factory()->count(10)->create();
        }

        $customers = Customer::limit(5)->get();
        $products = Product::limit(10)->get();

        $currentMonth = Carbon::now()->startOfMonth();
        $nextMonth = Carbon::now()->addMonth()->startOfMonth();

        DB::transaction(function () use ($customers, $products, $currentMonth, $nextMonth) {
            
            foreach ($customers as $index => $customer) {
                // Determine reliability of customer (for demo purposes)
                // Customer 1: Accurate Forecast
                // Customer 2: Under Forecast (Actual > Forecast)
                // Customer 3: Over Forecast (Actual < Forecast)
                
                foreach ($products as $pIndex => $product) {
                    // Only assign some products to each customer
                    if (($index + $pIndex) % 3 !== 0) continue; 

                    // 1. Create Forecast for Current Month
                    $forecastQty = rand(100, 1000);
                    SalesForecast::create([
                        'customer_id' => $customer->id,
                        'product_id' => $product->id,
                        'period' => $currentMonth,
                        'qty_forecast' => $forecastQty,
                        'notes' => 'Generated by SalesPlanningSeeder',
                    ]);

                    // 2. Create Forecast for Next Month (Growing)
                    SalesForecast::create([
                        'customer_id' => $customer->id,
                        'product_id' => $product->id,
                        'period' => $nextMonth,
                        'qty_forecast' => $forecastQty * 1.1,
                        'notes' => 'Projected growth',
                    ]);

                    // 3. Create Actual Sales (Sales Orders) for Current Month
                    // Variate based on customer index
                    $ratio = 1.0;
                    if ($index == 1) $ratio = 1.2; // Over achieve
                    if ($index == 2) $ratio = 0.6; // Under achieve

                    $actualQty = $forecastQty * $ratio;
                    
                    // Split actuals into 2-3 Orders
                    $numOrders = rand(2, 3);
                    $qtyPerOrder = $actualQty / $numOrders;

                    // Get a warehouse
                    $warehouseId = DB::table('warehouses')->first()->id ?? 1;
                    $companyId = $customer->company_id ?? 1;

                    for ($i = 0; $i < $numOrders; $i++) {
                        $orderDate = $currentMonth->copy()->addDays(rand(1, 25));
                        
                        $so = SalesOrder::create([
                            'company_id' => $companyId,
                            'customer_id' => $customer->id,
                            'warehouse_id' => $warehouseId,
                            'so_number' => 'SO-' . $customer->code . '-' . $orderDate->format('ymd') . '-' . rand(10, 99),
                            'order_date' => $orderDate,
                            'status' => 'confirmed', 
                            'total' => $qtyPerOrder * ($product->price ?? 10000), 
                            'subtotal' => $qtyPerOrder * ($product->price ?? 10000),
                            'notes' => 'Auto-generated for Sales Planning Demo',
                        ]);

                        SalesOrderItem::create([
                            'sales_order_id' => $so->id,
                            'product_id' => $product->id,
                            'description' => $product->name,
                            'qty' => $qtyPerOrder,
                            'unit_price' => $product->price ?? 10000,
                            'subtotal' => $qtyPerOrder * ($product->price ?? 10000),
                            // 'unit_id' => 1, // Optional, might need check
                        ]);
                    }

                    // 4. Create Delivery Schedules
                    // Some for these orders, some independent
                    $scheduleDate1 = $currentMonth->copy()->addDays(rand(1, 15)); // Past
                    DeliverySchedule::create([
                        'customer_id' => $customer->id,
                        'product_id' => $product->id,
                        'delivery_date' => $scheduleDate1,
                        'qty_scheduled' => $qtyPerOrder,
                        'po_number' => 'PO-' . rand(1000, 9999),
                        'notes' => 'Routine delivery',
                    ]);

                    $scheduleDate2 = Carbon::today()->addDays(rand(1, 7)); // Upcoming
                    DeliverySchedule::create([
                        'customer_id' => $customer->id,
                        'product_id' => $product->id,
                        'delivery_date' => $scheduleDate2,
                        'qty_scheduled' => $qtyPerOrder,
                        'po_number' => 'PO-' . rand(1000, 9999),
                        'notes' => 'Urgent request',
                    ]);
                    
                    // Create one delayed schedule (past date, no DO linked - implied)
                    if ($index == 0) {
                         DeliverySchedule::create([
                            'customer_id' => $customer->id,
                            'product_id' => $product->id,
                            'delivery_date' => Carbon::yesterday(),
                            'qty_scheduled' => 50,
                            'po_number' => 'PO-DELAYED',
                            'notes' => 'Production delay',
                        ]);
                    }
                }
            }
        });
    }
}
